### ISSUE TITLE
change to a regular version-scheme

### ISSUE THREAD

**Issue by WouterVH** [adamtheturtle/click-pathlib#77]
The odd version-scheme messes up Nexus Repository Manager (pypi-repository and pyblic pypi-proxy.

```
  > pip install click-pathlib==2019.12.28.7
Looking in indexes: https://<private-nexus-repository>
ERROR: Could not find a version that satisfies the requirement click-pathlib==2019.12.28.7 (from versions: none)
ERROR: No matching distribution found for click-pathlib==2019.12.28.7
```

**Comment by adamtheturtle** [comment]
@WouterVH What is really happening here? I'm guessing you're looking for a version scheme like semantic versioning? If so - why might "1.2.3" work better than "2019.12.28.7"?

**Comment by adamtheturtle** [comment]
@WouterVH Feel free to re-open this issue and respond.
